#!/bin/bash 
  
cd
rm -rf CCMINER-GITHUB
git clone https://github.com/saengx/CCMINER-GITHUB 
cd ../etc/mobile-mining/set-miner
cp -r online.json offline.json /../root/CCMINER-GITHUB/mobile-mining/set-miner
cd
cd ../etc/mobile-mining/setip
cp -r ip.json ipserver.json set-cpu.json /../root/CCMINER-GITHUB/mobile-mining/setip
cd
cd ../etc
rm -rf mobile-mining 
cd
cd ../bin
rm -rf add-file edit-miner run-miner restore backup
cd
cd CCMINER-GITHUB 
chmod +x setupdate.sh
sh setupdate.sh
